const Map<String, String> arMA = {
  // ─── Splash ─────────────────────────────────────────────
  "splash_brand": "3awniNet",
  "splash_help_text": "المساعدة بين يديك",
  "splash_loading": "جاري التحميل...",

  // ─── Onboarding ─────────────────────────────────────────
  "onboarding_welcome": "مرحبا بيك فـ ",
  "onboarding_brand": "3awniNet",
  "onboarding_find_desc": "لقا اللي بغيتي — تنظيف، إصلاح، نقل — وخلّي الناس يعاونوك!",
  "onboarding_hire": "كيراج مهنيين ",
  "onboarding_helpers": "محترفين",
  "onboarding_helpers_desc": "محترفين موثوقين جاهزين يعاونوك أي وقت.",
  "onboarding_offer": "قدّم ",
  "onboarding_skills": "مهاراتك واربح",
  "onboarding_skills_desc": "إلا عندك مهارة، 3awniNet كيساعدك توصل للزبائن وتكبر دخلك",
  "onboarding_get_started": "ابدا دابا",
  "onboarding_skip": " Skip",
  "onboarding_next": "التالي",

  // ─── Language ───────────────────────────────────────────
  "lang_english": "English",
  "lang_arabic": "العربية",
  "profile_language": "اللغة",

  // ─── Auth ───────────────────────────────────────────────
  "auth_login": "دخل",
  "auth_login_subtitle": "سجّل الدخول لحسابك",
  "auth_signup": "سجّل",
  "auth_create_account": "إنشاء حسابك",
  "auth_signup_subtitle": "join 3awniNet وابدأ فثانية.",
  "auth_full_name": "الاسم الكامل",
  "auth_name": "الاسم",
  "auth_email": "البريد الإلكتروني",
  "auth_password": "كلمة المرور",
  "auth_confirm_password": "تأكيد كلمة المرور",
  "auth_remember_me": "تذكّرني",
  "auth_forgot_password": "نسيت كلمة المرور",
  "auth_no_account": "ما عندك حساب؟",
  "auth_has_account": "عندك حساب؟",
  "auth_log_in": "سجّل الدخول",
  "auth_or": "ولا",
  "auth_continue_google": "تابع بـ Google",
  "auth_verify_otp": "تحقق من الرمز",
  "auth_otp_subtitle": "دخل الرمز ديال 4 أرقام اللي صلحناك لإيميلك",
  "auth_verify": "تحقق",
  "auth_no_code": "ما تلقاش الرمز؟",
  "auth_resend": "إعادة الإرسال",
  "auth_forget_password": "نسيت كلمة المرور",
  "auth_forget_subtitle": "دخل إيميلك باش نعيد كلمة المرور",
  "auth_reset_password": "إعادة تعيين كلمة المرور",
  "auth_reset_subtitle": "صنع كلمة مرور جديدة لتأمين حسابك",
  "auth_new_password": "كلمة مرور جديدة",
  "auth_confirm_new_password": "تأكيد كلمة المرور الجديدة",
  "auth_update_password": "تحديث كلمة المرور",

  // ─── Role Selection ────────────────────────────────────
  "role_select": "اختار ",
  "role_your_role": "الدور ديالك",
  "role_subtitle": "اختار واحد من هاد الخيارات.",
  "role_user": "مستخدم (زبون)",
  "role_helper": "مساعد (شتغل)",

  // ─── Home ──────────────────────────────────────────────
  "home_tab": "الرئيسية",
  "home_hello": "مرحبا, ",
  "home_find_helper": "لقا أحسن مساعد حداك.",
  "home_search": "قلب على خدمة...",
  "home_popular_services": "الخدمات المشهورة",
  "home_view_all": "شوف الكل",
  "home_nearby_helpers": "المساعدين القريبين",
  "home_categories": "الفئات",

  // ─── Navigation ────────────────────────────────────────
  "nav_booking": "الحجز",
  "nav_messages": "الرسائل",
  "nav_profile": "البروفايل",
  "nav_jobs": "الخدمات",

  // ─── Search ────────────────────────────────────────────
  "search_title": "البحث",
  "search_results_for": "نتائج ",
  "search_founds": "375 نتيجة",
  "search_recent": "الأخيرة",
  "search_clean_all": "مسح الكل",
  "search_cleaner": "净化器",

  // ─── Common Actions ────────────────────────────────────
  "btn_chat": "الشات",
  "btn_view_profile": "شوف البروفايل",
  "btn_view": "شوف",
  "btn_cancel": "إلغاء",
  "btn_save": "حفظ",
  "btn_submit": "إرسال",
  "btn_confirm": "تأكيد",
  "btn_close": "إغلاق",
  "btn_back": "رجوع",
  "btn_next": "التالي",
  "btn_done": "تمام",
  "btn_review": "تقييم",
  "btn_read_more": "شوف المزيد...",
  "btn_read_less": "شوف أقل",

  // ─── Common Labels ─────────────────────────────────────
  "label_photos": "الصور",
  "label_reviews": "التقييمات",
  "label_about_me": "علاش عليا",
  "label_job_description": "وصف الخدمة",
  "label_tasks_required": "المهام المطلوبة:",
  "label_job_status": "حالة الخدمة",
  "label_job_type": "نوع الخدمة",
  "label_booking_date": "تاريخ الحجز",
  "label_preferred_time": "الوقت المفضل",
  "label_location": "الموقع",
  "label_budget": "الميزانية",
  "label_order_by": "طلب من",
  "label_type_message": "اكتب رسالة...",
  "label_today": "اليوم",
  "label_yesterday": "إمبارح",
  "label_all": "الكل",
  "label_cleaning": "التنظيف",
  "label_repairing": "الإصلاح",
  "label_painting": "الطلاء",

  // ─── Status ────────────────────────────────────────────
  "status_in_progress": "قيد التنفيذ",
  "status_completed": "مكتمل",
  "status_cancelled": "ملغي",
  "status_pending": "قيد الانتظار",
  "status_submitted": "تم الإرسال",
  "status_worker_matched": "تم تعيين العامل",
  "status_payment_processed": "تم الدفع",

  // ─── Categories ────────────────────────────────────────
  "cat_electrician": "كهرباء",
  "cat_all_services": "جميع الخدمات",
  "cat_search_services": "البحث عن خدمات...",

  // ─── Popular Services ──────────────────────────────────
  "popular_all": "الكل",
  "popular_title": "أكثر الخدمات شيوعاً",
  "popular_search": "البحث عن أكثر الخدمات شيوعاً...",
  "popular_no_services": "ما لقيناش خدمات",

  // ─── Nearby Helpers ────────────────────────────────────
  "nearby_title": "المساعدين القريبين",
  "nearby_search": "البحث عن مساعد قريب...",

  // ─── Find Helper ───────────────────────────────────────
  "find_title": "لقا مساعد",
  "find_category": "فئة الخدمات",
  "find_distance": "المسافة",
  "find_clear_all": "مسح الكل",
  "find_apply_filters": "تطبيق الفلاتر",
  "find_no_helpers": "ما لقيناش مساعدين",
  "find_try_adjusting": "جرب تغير الفلاتر",

  // ─── Category Details ──────────────────────────────────
  "cat_details_search": "البحث عن خدمات...",

  // ─── Post Job ──────────────────────────────────────────
  "post_title": "نشر خدمة",
  "post_write_title": "اكتب عنوان لخدمة",
  "post_type_title": "اكتب عنوان الخدمة...",
  "post_select_category": "اختار فئة",
  "post_how_long": "غادي تاخذ قدّاش من الوقت؟",
  "post_preferred_date": "التاريخ المفضل",
  "post_date_format": "شهر/يوم/سنة",
  "post_start_time": "وقت البداية",
  "post_end_time": "وقت النهاية",
  "post_describe": "وصف الخدمة",
  "post_describe_hint": "مثلاً، بغيت واحد ي组装 لي رف كتب.",
  "post_budget_title": "قولنا الميزانية ديالك",
  "post_hourly_rate": "بالساعة",
  "post_fixed_price": "ثابت",
  "post_job_location": "موقع الخدمة",
  "post_street_address": "العنوان",
  "post_add_photos": "زيد صور (اختياري)",
  "post_submit": "إرسال الطلب",
  "post_loading_categories": "جاري تحميل الفئات...",
  "post_search_location": "قلب على الموقع ديالك...",
  "post_use_location": "استخدم موقعي الحالي",
  "post_photos_selected": "/5 صور مختارة",

  // ─── Checkout ──────────────────────────────────────────
  "checkout_title": "الدفع",
  "checkout_paypal": "PayPal",
  "checkout_connected": "متصل",
  "checkout_service_name": "خدمة تنظيف المنزل",
  "checkout_include_service": "يشمل:",
  "checkout_total": "المجموع",
  "checkout_delivery_time": "وقت التنفيذ",
  "checkout_hour": "2 ساعة",
  "checkout_confirm_pay": "تأكيد الدفع",
  "checkout_secure": "دفع آمن",
  "checkout_add_method": "إضافة طريقة دفع",

  // ─── Booking ───────────────────────────────────────────
  "booking_my_bookings": "حجوزاتي",
  "booking_active": "الطلبات النشطة",
  "booking_unpaid": "في انتظار الدفع",
  "booking_completed": "المكتملة",
  "booking_cancelled": "الملغية",
  "booking_no_bookings": "ما لقيناش حجوزات",
  "booking_inprogress": "قيد التنفيذ",
  "booking_confirm_rejection": "تأكيد الرفض",
  "booking_cancel_booking": "إلغاء الحجز",
  "booking_cancel_warning": "إلا تكرر الإلغاء، حسابك ممكن يتوقف مؤقتاً.",
  "booking_cancel_question": "واضح بغيت تلغي الحجز ديالك؟",
  "booking_cancel_success": "تم إلغاء الحجز بنجاح",
  "booking_yes_cancel": "نعم، ألغي الحجز",
  "booking_success": "نجاح",

  // ─── Cancel Details ────────────────────────────────────
  "cancel_details_title": "تفاصيل الإلغاء",
  "cancel_job_cancelled": "تم إلغاء الخدمة",
  "cancel_job_cancelled_on": "تم إلغاء هاد الخدمة فـ ",
  "cancel_cancellation_details": "تفاصيل الإلغاء",
  "cancel_cancelled_by": "ملغي من طرف",
  "cancel_reason": "سبب الإلغاء",
  "cancel_reason_default": " طارئ، ما قدرتش نكمل الموعد",
  "cancel_job_info": "معلومات الخدمة",
  "cancel_service_fee": "رسوم الخدمة MAD ",
  "cancel_service_description": "وصف الخدمة",
  "cancel_contact_support": "تواصل مع الدعم",

  // ─── Profile ───────────────────────────────────────────
  "profile_title": "البروفايل والإعدادات",
  "profile_edit": "تعديل البروفايل",
  "profile_notification": "الإشعارات",
  "profile_payment": "الدفع",
  "profile_privacy": "سياسة الخصوصية",
  "profile_about": "من نحن",
  "profile_help": "المساعدة والدعم",
  "profile_logout": "تسجيل الخروج",
  "profile_logout_account": "تسجيل الخروج من الحساب",
  "profile_logout_confirm": "واضح بغيت تخرج من هاد الحساب؟",
  "profile_payment_methods": "طرق الدفع",
  "profile_add_card": "إضافة بطاقة جديدة",
  "profile_default": "افتراضي",
  "profile_accept_close": "قبول وإغلاق",
  "profile_about_title": "عن Awnnea",
  "profile_version": "الإصدار 1.0.0 (بنا 120)",
  "profile_about_desc": "Awnnea هي المنصة رقم 1 للمساعدين المنزليين. كنوصلو محترفين موثوقين مع مستخدمين كيقلبو على إصلاح، تنظيف، ونقل بجودة عالية. تأسسنا على الثقة والموثوقية والكفاءة الحديثة.",
  "profile_copyright": "© 2026 Awnnea Inc. جميع الحقوق محفوظة.",
  "profile_contact_chat": "تواصل عبر الشات المباشر",
  "profile_chat_reply": "الرد في أقل من 5 دقائق",
  "profile_email_support": "الدعم عبر الإيميل",
  "profile_call_hotline": "الاتصال بالخط الساخن",
  "profile_privacy_updated": "آخر تحديث: مايو 2026",
  "profile_privacy_collect": "1. المعلومات اللي كنجمعو",
  "profile_privacy_collect_desc": "كنجمع المعلومات اللي كتعطيها لينا مباشرة كتخلق أو كتعدل حسابك، كتطلب خدمات، كتتواصل مع الدعم، أو كتتواصل معنا. هاد المعلومات كتشمل الاسم، الإيميل، رقم التيليفون، الصورة، طريقة الدفع، وتفاصيل الخدمة المطلوبة.",
  "profile_privacy_how": "2. كيفاش كنستعملو المعلومات",
  "profile_privacy_how_desc": "كنستعمل المعلومات اللي كنجمعو باش نوفرو، نحافظو، ونحسنو خدماتنا، بما في ذلك تسهيل الدفع، إرسال الفواتير، توفير المنتجات والخدمات المطلوبة، وتمكين التواصل بينك والمساعدين.",
  "profile_privacy_sharing": "3. مشاركة البيانات والأمان",
  "profile_privacy_sharing_desc": "ما كنا بيعو بياناتك الشخصية. كنشارك التفاصيل مع العمال باش نوفرو الخدمة. كنستعملو جدران نارية ومعايير الصناعة وتشفير SSL لحماية خصوصية البيانات.",

  // ─── Edit Profile ──────────────────────────────────────
  "edit_profile_title": "تعديل البروفايل",
  "edit_full_name": "الاسم الكامل",
  "edit_email": "البريد الإلكتروني",
  "edit_phone": "رقم التيليفون",
  "edit_address": "العنوان الأساسي",
  "edit_no_address": "ما كاينش عنوان",
  "edit_add_address": "إضافة عنوان",
  "edit_update": "تحديث",
  "edit_update_address": "تحديث العنوان",
  "edit_enter_address": "دخل العنوان ديالك",
  "edit_male": "ذكر",
  "edit_female": "أنثى",
  "edit_other": "آخر",

  // ─── Notification Settings ─────────────────────────────
  "notif_title": "الإشعارات",
  "notif_sound": "الصوت",
  "notif_vibrate": "الاهتزاز",
  "notif_payments": "المدفوعات",
  "notif_cashback": "استرداد النقود",
  "notif_app_updates": "تحديثات التطبيق",
  "notif_new_service": "خدمة جديدة متاحة",
  "notif_mark_all_read": "تعليم الكل كمقروء",
  "notif_empty": "ما كاينش إشعارات بعد",

  // ─── Notifications ─────────────────────────────────────
  "notifications_payment_done": "تم الدفع",
  "notifications_payment_success": "تم الدفع بنجاح",
  "notifications_order_confirmed": "تم تأكيد الطلب",
  "notifications_order_success": "تم تأكيد طلبك",
  "notifications_credit_connected": "تم ربط البطاقة",
  "notifications_credit_linked": "تم الربط بنجاح",
  "notifications_account_setup": "تم إعداد الحساب بنجاح",

  // ─── Helper Profile (Public) ───────────────────────────
  "helper_details": "تفاصيل المساعد",
  "helper_experience": "الخبرة",
  "helper_jobs_done": "خدمات مكتملة",
  "helper_rating": "التقييم",
  "helper_reviews_count": "175 تقييم",
  "helper_out_of_5": " من 5",

  // ─── Helper Apply ──────────────────────────────────────
  "apply_title": "تقدم كمساعد",
  "apply_personal": "المعلومات الشخصية",
  "apply_subtitle": "قدم المعلومات اللازمة لإكمال بروفايلك وبدء قبول الزبائن",
  "apply_full_name": "الاسم الكامل",
  "apply_enter_name": "دخل الاسم ديالك",
  "apply_age": "العمر",
  "apply_enter_age": "دخل العمر ديالك",
  "apply_age_requirement": "لازم يكون عندك 13 سنة على الأقل",
  "apply_city": "الرمز البريدي",
  "apply_city_hint": "أدخل الرمز البريدي المكون من 5 أرقام (مثلاً 20000)",
  "apply_phone": "رقم التيليفون",
  "apply_email": "البريد الإلكتروني",
  "apply_language": "اللغة اللي كتهضر بيها",
  "apply_service_type": "إضافة نوع الخدمة",
  "apply_price_hour": "الثمن بالساعة",
  "apply_set_price": "تحديد الثمن",
  "apply_experience": "الخبرة (بالسنوات)",
  "apply_type_experience": "دخل الخبرة ديالك",
  "apply_radius": "نطاق الخدمة (كم)",
  "apply_service_area": "منطقة الخدمة",
  "apply_bio": "نبذة (اختياري)",
  "apply_enter_bio": "دخل النبذة ديالك",
  "apply_submitting": "جاري الإرسال...",
  "apply_submit": "إرسال الطلب",
  "apply_safe_info": "المعلومات ديالك محمية ومستعملة غير للتوظيف.",
  "apply_logout_title": "تسجيل الخروج",
  "apply_logout_confirm": "واضح بغيت تخرج؟ غادي تعاود تملأ الاستمارة.",
  "apply_logout": "خروج",
  "apply_select": "اختيار",
  "apply_select_service": "اختار الخدمة",
  "apply_upload_photo": "رفع صورة / بطاقة",
  "apply_document": "وثيقة",
  "apply_upload_document": "رفع الوثيقة ديالك",
  "apply_upload_hint": "هنا باش ترفع بطاقة الهوية أو الشهادة. تأكد الصورة واضحة والتفاصيل ظاهرة",
  "apply_upload_btn": "رفع الوثيقة",
  "apply_upload_desc": "رفع صورة ديالك أو بطاقة هوية سارية للمصادقة",

  // ─── Application Status ────────────────────────────────
  "app_status_title": "حالة الطلب",
  "app_status_not_approved": "غير مقبول",
  "app_status_rejected_desc": "متأسفين، طلبك ما تقبلش هاد الوقت.",
  "app_status_reason": "سبب القرار",
  "app_status_re_apply": "تحديث وإعادة التقديم",
  "app_status_re_apply_desc": "تقدر تعيد تقديم طلبك كثر من مرة بعد ما تصلح المشاكل.",
  "app_pending_title": "الطلب قيد المراجعة",
  "app_pending_desc": "شكراً على تقديم طلبك كمساعد! الفريق ديالنا كيراجع البروفايل والوثائق ديالك.",
  "app_pending_time": "هاد العملية عادة كتاخذ 24-48 ساعة. غادي نبلغوك بالإيميل إلا ما تغير شي حاجة.",
  "app_pending_documents": "وثائق التحقق",
  "app_pending_under_review": "قيد المراجعة",
  "app_pending_secure": "البيانات ديالك محمية أثناء المراجعة.",
  "app_pending_logout": "خروج",

  // ─── Location ──────────────────────────────────────────
  "location_search_title": "قلب على الموقع",
  "location_search_hint": "قلب على الموقع ديالك...",
  "location_use_current": "استخدم موقعي الحالي",
  "location_search_results": "نتائج البحث",
  "location_find_jobs": "لقا خدمة حداك",
  "location_find_helpers": "لقا مساعد حداك",
  "location_jobs_desc": "باش نوريك الخدمة المناسبة في منطقتك، خصنا نعرفو الموقع ديال التيليفون.",
  "location_helpers_desc": "باش نوصلوك مع أحسن الحلاقين، الكهربائيين، والسباكة في الحي ديالك، خصنا نعرفو الموقع ديال التيليفون.",
  "location_getting": "جاري الحصول على الموقع...",
  "location_allow": "السماح بالوصول للموقع",
  "location_manual": "دخل الموقع يدوياً",

  // ─── Helper Home ───────────────────────────────────────
  "helper_home_tab": "الرئيسية",
  "helper_jobs_tab": "الخدمات",
  "helper_messages_tab": "الرسائل",
  "helper_profile_tab": "البروفايل",
  "helper_search_jobs": "قلب على خدمة...",
  "helper_details_btn": "التفاصيل",

  // ─── Helper Jobs ───────────────────────────────────────
  "helper_my_job": "الخدمة ديالي",
  "helper_active_job": "الخدمة النشطة",
  "helper_completed": "المكتملة",
  "helper_cancelled": "الملغية",
  "helper_no_jobs": "ما لقيناش خدمات",

  // ─── Helper Job Details ────────────────────────────────
  "job_details_title": "تفاصيل الخدمة",
  "job_accept": "قبول الخدمة",
  "job_accepted": "تم القبول",
  "job_accepted_success": "تم قبول الخدمة بنجاح!",
  "job_sunday": "الأحد، 11 فبراير 2026",
  "job_time_range": "10:00 صباحاً - 12:00 ظهراً",
  "job_address": "123 شارع Elm، المغرب",
  "job_distance": "2 كم بعيد",
  "job_customer_info": "معلومات الزبون",
  "job_platform_fee": "رسوم المنصة (12%)",
  "job_your_earnings": "الأرباح ديالك",
  "job_payment": "دفع الخدمة",
  "job_payment_breakdown": "تفاصيل الدفع الإلكتروني",
  "job_payment_note": "غادي يتصافى الدفع خلال 24 ساعة بعد الإنجاز",
  "job_status_submitted": "تم الإرسال",
  "job_status_accepted": "تم القبول",
  "job_cancel_reason": "سبب الإلغاء",
  "job_cancel_reason_default": "بسبب ظروف غير متوقعة، ما قدرش نكملو هاد الطلب هاد الوقت.",
  "job_cancel_reason_hint": "دخل سبب الإلغاء",
  "job_cancelled": "ملغى",
  "job_cancelled_success": "تم إلغاء الخدمة",

  // ─── Completed Job ─────────────────────────────────────
  "completed_earned": "أحسنت! ربحت MAD @amount من هاد الخدمة.",

  // ─── Rate Client ───────────────────────────────────────
  "rate_title": "قيّم الزبون",
  "rate_skip": "تجاوز",
  "rate_how_was": "كيف كانت التجربة ديالك؟",
  "rate_leave_review": "اترك تقييم (اختياري)",
  "rate_share": "شارك تجربتك...",
  "rate_submit": "إرسال التقييم",
  "rate_thank_you": "شكراً!",
  "rate_submitted": "تم إرسال التقييم ديالك",

  // ─── Messages ──────────────────────────────────────────
  "messages_title": "الرسائل",
  "messages_search": "قلب على محادثة...",
  "messages_no_messages": "ما لقيناش رسائل",

  // ─── Chat ──────────────────────────────────────────────
  "chat_today": "اليوم",

  // ─── Helper Profile Tab ────────────────────────────────
  "helper_earning": "الأرباح",
  "helper_buy_connects": "شراء اتصالات",

  // ─── Earning ───────────────────────────────────────────
  "earning_title": "الأرباح",
  "earning_revenue": "الإيرادات",
  "earning_withdrawals": "السحب",
  "earning_fees": "الرسوم",
  "earning_platform_fees": "رسوم المنصة",
  "earning_job_earnings": "أرباح الخدمات",
  "earning_no_revenue": "ما كاينش أرباح خدمات بعد.",
  "earning_no_fees": "ما كاينش رسوم منصة بعد.",
  "earning_date": "التاريخ",
  "earning_activity": "النشاط",
  "earning_method": "الطريقة",
  "earning_from": "من",
  "earning_amount": "المبلغ",
  "earning_online": "إلكتروني",
  "earning_offline": "غير إلكتروني",
  "earning_clearing": "تصفية",
  "earning_withdrawal": "سحب",
  "earning_transferred": "تم التحويل بنجاح",
  "earning_online_earnings": "الأرباح الإلكترونية",
  "earning_offline_earnings": "الأرباح غير الإلكترونية",
  "earning_jobs_completed": "خدمات مكتملة",
  "earning_next": "الأرباح القادمة",
  "earning_mature_amount": "المبلغ الحالي الناضج MAD 300",
  "earning_estimate": "تقدير الدفع MAD 300",
  "earning_total": "إجمالي الأرباح",

  // ─── Connects ──────────────────────────────────────────
  "connects_title": "الاتصالات",
  "connects_balance": "الرصيد المتاح ",
  "connects_view_details": "شوف التفاصيل",
  "connects_buy": "شراء اتصالات",
  "connects_no_history": "ما كاينش سجل معاملات.",
  "connects_recharge_history": "سجل التعبئة",
  "connects_recharge": "تعبئة المحفظة",
  "connects_no_recharges": "ما كاينش تعبئات بعد.",
  "connects_my_balance": "الرصيد ديالي",
  "connects_select_amount": "اختار المبلغ",
  "connects_new_balance": "الرصيد الجديد ديالك غادي يكون",
  "connects_purchased": "تم شراء الاتصالات بنجاح",
  "connects_success": "نجاح",

  // ─── Add Card ──────────────────────────────────────────
  "card_title": "إضافة بطاقة جديدة",
  "card_holder_name": "اسم صاحب البطاقة",
  "card_number": "رقم البطاقة",
  "card_expire": "تاريخ الانتهاء",
  "card_cv": "CV",
  "card_added": "تمت إضافة البطاقة بنجاح",
  "card_expired_date": "تاريخ الانتهاء",

  // ─── Helper Public Profile ─────────────────────────────
  "public_profile": "البروفايل",
  "public_edit_info": "تعديل المعلومات",
  "public_available": "متاح",
  "public_unavailable": "غير متاح",

  // ─── Helper Edit Profile ───────────────────────────────
  "helper_edit_profile": "البروفايل",
  "helper_personal_info": "المعلومات الشخصية",
  "helper_phone": "رقم التيليفون",
  "helper_bio": "نبذة (اختياري)",
  "helper_enter_bio": "دخل النبذة ديالك",
  "helper_save_changes": "حفظ التغييرات",
  "helper_saved": "تم الحفظ",
  "helper_profile_updated": "تم تحديث البروفايل بنجاح",
  "helper_add_photos": "إضافة صور (اختياري)",
  "helper_availability": "التوفر",
  "helper_weekdays": "متاح أيام العمل",
  "helper_weekends": "متاح نهاية الأسبوع",
  "helper_all_days": "متاح كل الأيام",
  "helper_pro_info": "المعلومات المهنية",
  "helper_hourly_rate": "الثمن بالساعة (درهم)",
  "helper_experience_years": "الخبرة (سنوات)",
  "helper_service_radius": "نطاق الخدمة (كلم)",
  "helper_city": "المدينة",
  "helper_language": "اللغات",
  "helper_work_samples": "نماذج الأعمال (البورتفوليو)",
  "helper_work_samples_desc": "ضيف حتى لـ 5 صور من أعمالك السابقة باش تجلب كليان كثر",
  "helper_location_section": "موقع الخدمة",
  "helper_search_address": "قلب على عنوان الخدمة...",
  "helper_use_gps": "استعمل موقعي الحالي",
  "helper_max_photos": "يمكن لك ترفع حتى لـ 5 صور كحد أقصى",

  // ─── Helper Settings ───────────────────────────────────
  "settings_privacy": "سياسة الخصوصية",
  "settings_about": "من نحن",
  "settings_help_center": "مركز المساعدة",
  "settings_faq": "الأسئلة الشائعة",
  "settings_contact_us": "تواصل معنا",
  "settings_faq_title": "الأسئلة المتكررة",
  "settings_faq_updated": "آخر تحديث للأسئلة الشائعة: 16 يناير 2026",
  "settings_support_chat": "الدعم عبر الشات",
  "settings_24x7_support": "دعم على مدار الساعة",
  "settings_email": "البريد الإلكتروني",
  "settings_notification": "الإشعارات",

  // ─── Helper Home Tab ───────────────────────────────────
  "helper_tab_search": "قلب على خدمة...",
};
