const Map<String, String> enUS = {
  // ─── Splash ─────────────────────────────────────────────
  "splash_brand": "3awniNet",
  "splash_help_text": "Help is in your hands.",
  "splash_loading": "Loading...",

  // ─── Onboarding ─────────────────────────────────────────
  "onboarding_welcome": "Welcome to ",
  "onboarding_brand": "3awniNet",
  "onboarding_find_desc": "Find what you need — cleaning, fixing, moving — and let others help!",
  "onboarding_hire": "Hire Nearby ",
  "onboarding_helpers": "skilled Helpers",
  "onboarding_helpers_desc": "Verified helpers ready to assist you anytime.",
  "onboarding_offer": "Offer your ",
  "onboarding_skills": "skills and earn",
  "onboarding_skills_desc": "If you have a skill, 3awniNet helps you connect with clients and grow your income",
  "onboarding_get_started": "Get Started",
  "onboarding_skip": "Skip",
  "onboarding_next": "Next",

  // ─── Language ───────────────────────────────────────────
  "lang_english": "English",
  "lang_arabic": "العربية",
  "profile_language": "Language",

  // ─── Auth ───────────────────────────────────────────────
  "auth_login": "Login",
  "auth_login_subtitle": "Sign in to my account",
  "auth_signup": "Sign Up",
  "auth_create_account": "Create Your Account",
  "auth_signup_subtitle": "Join 3awniNet and get started in seconds.",
  "auth_full_name": "Full name",
  "auth_name": "Name",
  "auth_email": "Email",
  "auth_password": "Password",
  "auth_confirm_password": "Confirm Password",
  "auth_remember_me": "Remember Me",
  "auth_forgot_password": "Forgot Password",
  "auth_no_account": "Don't have an account?",
  "auth_has_account": "Already have an account?",
  "auth_log_in": "Log In",
  "auth_or": "OR",
  "auth_continue_google": "Continue with Google",
  "auth_verify_otp": "Verify OTP",
  "auth_otp_subtitle": "Please enter the 4-digit code sent to your email",
  "auth_verify": "Verify",
  "auth_no_code": "Didn't receive the code?",
  "auth_resend": "Resend",
  "auth_forget_password": "Forget Password",
  "auth_forget_subtitle": "Please enter your email to reset password",
  "auth_reset_password": "Reset Password",
  "auth_reset_subtitle": "Create a new password to secure your account",
  "auth_new_password": "New Password",
  "auth_confirm_new_password": "Confirm New Password",
  "auth_update_password": "Update Password",

  // ─── Role Selection ────────────────────────────────────
  "role_select": "Select ",
  "role_your_role": "Your Role",
  "role_subtitle": "Choose one from these options.",
  "role_user": "User (Client)",
  "role_helper": "Helper (Worker)",

  // ─── Home ──────────────────────────────────────────────
  "home_tab": "Home",
  "home_hello": "Hello, ",
  "home_find_helper": "Find the best helper around you.",
  "home_search": "Search for a service...",
  "home_popular_services": "Popular Services",
  "home_view_all": "View All",
  "home_nearby_helpers": "Nearby Helpers",
  "home_categories": "Categories",

  // ─── Navigation ────────────────────────────────────────
  "nav_booking": "Booking",
  "nav_messages": "Messages",
  "nav_profile": "Profile",
  "nav_jobs": "Jobs",

  // ─── Search ────────────────────────────────────────────
  "search_title": "Search",
  "search_results_for": "Results for ",
  "search_founds": "375 founds",
  "search_recent": "Recent",
  "search_clean_all": "Clean All",
  "search_cleaner": "Cleaner",

  // ─── Common Actions ────────────────────────────────────
  "btn_chat": "Chat",
  "btn_view_profile": "View Profile",
  "btn_view": "View",
  "btn_cancel": "Cancel",
  "btn_save": "Save",
  "btn_submit": "Submit",
  "btn_confirm": "Confirm",
  "btn_close": "Close",
  "btn_back": "Back",
  "btn_next": "Next",
  "btn_done": "Done",
  "btn_review": "Review",
  "btn_read_more": "Read more...",
  "btn_read_less": "Read less",

  // ─── Common Labels ─────────────────────────────────────
  "label_photos": "Photos",
  "label_reviews": "Reviews",
  "label_about_me": "About me",
  "label_job_description": "Job Description",
  "label_tasks_required": "Tasks Required:",
  "label_job_status": "Job Status",
  "label_job_type": "Job Type",
  "label_booking_date": "Booking Date",
  "label_preferred_time": "Preferred Time",
  "label_location": "Location",
  "label_budget": "Budget",
  "label_order_by": "Order By",
  "label_type_message": "Type a message...",
  "label_today": "Today",
  "label_yesterday": "Yesterday",
  "label_all": "All",
  "label_cleaning": "Cleaning",
  "label_repairing": "Repairing",
  "label_painting": "Painting",

  // ─── Status ────────────────────────────────────────────
  "status_in_progress": "In Progress",
  "status_completed": "Completed",
  "status_cancelled": "Cancelled",
  "status_pending": "Pending",
  "status_submitted": "Job Submitted",
  "status_worker_matched": "Worker Matched",
  "status_payment_processed": "Payment Processed",

  // ─── Categories ────────────────────────────────────────
  "cat_electrician": "Electrician",
  "cat_all_services": "All Services",
  "cat_search_services": "Search Services...",

  // ─── Popular Services ──────────────────────────────────
  "popular_all": "All",
  "popular_title": "Most popular services",
  "popular_search": "Search for a Most popular services.....",
  "popular_no_services": "No services found",

  // ─── Nearby Helpers ────────────────────────────────────
  "nearby_title": "Nearby Helpers",
  "nearby_search": "Search for nearby helper.....",

  // ─── Find Helper ───────────────────────────────────────
  "find_title": "Find Helpers",
  "find_category": "Services Category",
  "find_distance": "Distance",
  "find_clear_all": "Clear All",
  "find_apply_filters": "Apply Filters",
  "find_no_helpers": "No helpers found",
  "find_try_adjusting": "Try adjusting your filters",

  // ─── Category Details ──────────────────────────────────
  "cat_details_search": "Search Services...",

  // ─── Post Job ──────────────────────────────────────────
  "post_title": "Post a job",
  "post_write_title": "Write a title for your job post",
  "post_type_title": "Type your job title...",
  "post_select_category": "Select a category",
  "post_how_long": "How long will your work take?",
  "post_preferred_date": "Preferred Date",
  "post_date_format": "mm/dd/yyyy",
  "post_start_time": "Start time",
  "post_end_time": "End time",
  "post_describe": "Describe your job",
  "post_describe_hint": "e.g., I need someone to assemble a new bookshelf.",
  "post_budget_title": "Tell us your budget",
  "post_hourly_rate": "Hourly rate",
  "post_fixed_price": "Fixed price",
  "post_job_location": "Job Location",
  "post_street_address": "Street Address",
  "post_add_photos": "Add photos (optional)",
  "post_submit": "Post Request",
  "post_loading_categories": "Loading categories...",
  "post_search_location": "Search your location...",
  "post_use_location": "Use my current location",
  "post_photos_selected": "/5 photos selected",

  // ─── Checkout ──────────────────────────────────────────
  "checkout_title": "Checkout",
  "checkout_paypal": "PayPal",
  "checkout_connected": "Connected",
  "checkout_service_name": "Home Cleaning Service",
  "checkout_include_service": "Include Service:",
  "checkout_total": "Total",
  "checkout_delivery_time": "Delivery Time",
  "checkout_hour": "2 hour",
  "checkout_confirm_pay": "Confirm & Pay",
  "checkout_secure": "Secure Payment",
  "checkout_add_method": "Add New Method",

  // ─── Booking ───────────────────────────────────────────
  "booking_my_bookings": "My Bookings",
  "booking_awaiting": "Awaiting",
  "booking_active": "Active Order",
  "booking_unpaid": "Awaiting Payment",
  "booking_completed": "Completed",
  "booking_cancelled": "Cancelled",
  "booking_no_bookings": "No bookings found",
  "booking_inprogress": "Inprogress",
  "booking_confirm_rejection": "Confirm Rejection",
  "booking_cancel_booking": "Cancel Booking",
  "booking_cancel_warning": "If cancellations happen repeatedly, your account may be temporarily suspended.",
  "booking_cancel_question": "Are you sure want to cancel your service booking?",
  "booking_cancel_success": "Booking cancelled successfully",
  "booking_yes_cancel": "Yes, Cancel Booking",
  "booking_success": "Success",

  // ─── Cancel Details ────────────────────────────────────
  "cancel_details_title": "Cancel Details",
  "cancel_job_cancelled": "Job Cancelled",
  "cancel_job_cancelled_on": "This job was cancelled on ",
  "cancel_cancellation_details": "Cancellation Details",
  "cancel_cancelled_by": "Cancelled by",
  "cancel_reason": "Reason for cancellation",
  "cancel_reason_default": "Emergency came up, unable to fulfill the appointment",
  "cancel_job_info": "Job Information",
  "cancel_service_fee": "Service Fee MAD ",
  "cancel_service_description": "Service Description",
  "cancel_contact_support": "Contact Support",

  // ─── Profile ───────────────────────────────────────────
  "profile_title": "Profile & Settings",
  "profile_edit": "Edit Profile",
  "profile_notification": "Notification",
  "profile_payment": "Payment",
  "profile_privacy": "Privacy Policy",
  "profile_about": "About US",
  "profile_help": "Help & Support",
  "profile_logout": "Logout",
  "profile_logout_account": "Logout Account",
  "profile_logout_confirm": "Are you sure to logout from this account?",
  "profile_payment_methods": "Payment Methods",
  "profile_add_card": "Add New Card",
  "profile_default": "Default",
  "profile_accept_close": "Accept & Close",
  "profile_about_title": "About Awnnea",
  "profile_version": "Version 1.0.0 (Build 120)",
  "profile_about_desc": "Awnnea is the #1 on-demand household helper platform. We connect verified professionals with users seeking high-quality repairs, cleaning, shifting, and shifting services. Founded on trust, reliability, and modern efficiency.",
  "profile_copyright": "© 2026 Awnnea Inc. All rights reserved.",
  "profile_contact_chat": "Contact via Live Chat",
  "profile_chat_reply": "Typical reply under 5 mins",
  "profile_email_support": "Email Support",
  "profile_call_hotline": "Call Hotline",
  "profile_privacy_updated": "Last Updated: May 2026",
  "profile_privacy_collect": "1. Information We Collect",
  "profile_privacy_collect_desc": "We collect information you provide directly to us when creating or modifying your account, requesting on-demand services, contacting support, or otherwise communicating with us. This info includes name, email, phone number, profile photo, payment method, and details of services requested.",
  "profile_privacy_how": "2. How We Use the Information",
  "profile_privacy_how_desc": "We use the information we collect to provide, maintain, and improve our Services, including facilitating payments, sending receipts, providing products and services you request, and enabling communications between you and helpers.",
  "profile_privacy_sharing": "3. Data Sharing & Security",
  "profile_privacy_sharing_desc": "We do not sell your personal data. We share details with workers to facilitate service delivery. We utilize standard industry firewalls and SSL encryption to safeguard data privacy.",

  // ─── Edit Profile ──────────────────────────────────────
  "edit_profile_title": "Edit Profile",
  "edit_full_name": "Full name",
  "edit_email": "Email",
  "edit_phone": "Phone number",
  "edit_address": "Primary address",
  "edit_no_address": "No address set",
  "edit_add_address": "Add new address",
  "edit_update": "Update",
  "edit_update_address": "Update Address",
  "edit_enter_address": "Enter your address",
  "edit_male": "Male",
  "edit_female": "Female",
  "edit_other": "Other",

  // ─── Notification Settings ─────────────────────────────
  "notif_title": "Notification",
  "notif_sound": "Sound",
  "notif_vibrate": "Vibrate",
  "notif_payments": "Payments",
  "notif_cashback": "Cashback",
  "notif_app_updates": "App Updates",
  "notif_new_service": "New Service Available",
  "notif_mark_all_read": "Mark all read",
  "notif_empty": "No notifications yet",

  // ─── Notifications ─────────────────────────────────────
  "notifications_payment_done": "Payment Done",
  "notifications_payment_success": "Your payment has been done successfully",
  "notifications_order_confirmed": "Order Confirmed",
  "notifications_order_success": "Your order has been confirmed",
  "notifications_credit_connected": "Credit Card Connected",
  "notifications_credit_linked": "Credit Card has been Linked",
  "notifications_account_setup": "Account Setup Successful",

  // ─── Helper Profile (Public) ───────────────────────────
  "helper_details": "Helper details",
  "helper_experience": "Experience",
  "helper_jobs_done": "Jobs Done",
  "helper_rating": "Rating",
  "helper_reviews_count": "175 Reviews",
  "helper_out_of_5": " OUT OF 5",

  // ─── Helper Apply ──────────────────────────────────────
  "apply_title": "Apply as a Helper",
  "apply_personal": "Personal Information",
  "apply_subtitle": "Provide the necessary information to complete your profile and start accepting clients",
  "apply_full_name": "Full Name",
  "apply_enter_name": "Enter your full name",
  "apply_age": "Age",
  "apply_enter_age": "Enter your age",
  "apply_age_requirement": "Must be 13 or older to apply",
  "apply_city": "Zip Code",
  "apply_city_hint": "Enter 5-digit zip code (e.g. 20000)",
  "apply_phone": "Phone Number",
  "apply_email": "Email Address",
  "apply_language": "Language Spoken",
  "apply_service_type": "Add Service Type",
  "apply_price_hour": "Price Per Hour",
  "apply_set_price": "Set price",
  "apply_experience": "Experience (in Years)",
  "apply_type_experience": "Type your experience",
  "apply_radius": "Service Radius (KM)",
  "apply_service_area": "Service area",
  "apply_bio": "Bio (optional)",
  "apply_enter_bio": "Enter your bio",
  "apply_submitting": "Submitting...",
  "apply_submit": "Submit Application",
  "apply_safe_info": "Your information is safe and only used for job matching.",
  "apply_logout_title": "Logout Account",
  "apply_logout_confirm": "Are you sure to logout? You will need to fill the form again.",
  "apply_logout": "Logout",
  "apply_select": "Select",
  "apply_select_service": "Select Service",
  "apply_upload_photo": "Upload Photo / ID",
  "apply_document": "Document",
  "apply_upload_document": "Upload Your Document",
  "apply_upload_hint": "Tap here to upload ID or Certificate. Ensure the image is clear and all details are visible",
  "apply_upload_btn": "Upload Document",
  "apply_upload_desc": "Upload a photo of yourself or a valid ID for verification",

  // ─── Application Status ────────────────────────────────
  "app_status_title": "Application Status",
  "app_status_not_approved": "NOT APPROVED",
  "app_status_rejected_desc": "We're sorry, but your application couldn't be approved at this time.",
  "app_status_reason": "REASON FOR DECISION",
  "app_status_re_apply": "Update & Re-apply",
  "app_status_re_apply_desc": "You can re-submit your application as many times as needed after fixing the issues.",
  "app_pending_title": "Application Pending",
  "app_pending_desc": "Thank you for applying to be a Helper! Our team is currently reviewing your profile and documents.",
  "app_pending_time": "This process usually takes 24-48 hours. We'll notify you via email as soon as there's an update.",
  "app_pending_documents": "Verification Documents",
  "app_pending_under_review": "Under Review",
  "app_pending_secure": "Your data is stored securely during review.",
  "app_pending_logout": "Log out",

  // ─── Location ──────────────────────────────────────────
  "location_search_title": "Search Your Location",
  "location_search_hint": "Search your location...",
  "location_use_current": "Use my current location",
  "location_search_results": "Search Results",
  "location_find_jobs": "Find Jobs Near You",
  "location_find_helpers": "Find Helpers Near You",
  "location_jobs_desc": "To show you relevant jobs in your area, we need access to your device's location.",
  "location_helpers_desc": "To connect you with the best barbers, electricians, and plumbers in your neighbourhood, we need access to your device's location.",
  "location_getting": "Getting Location...",
  "location_allow": "Allow Location Access",
  "location_manual": "Enter Location manually",

  // ─── Helper Home ───────────────────────────────────────
  "helper_home_tab": "Home",
  "helper_jobs_tab": "Jobs",
  "helper_messages_tab": "Messages",
  "helper_profile_tab": "Profile",
  "helper_search_jobs": "Search jobs...",
  "helper_details_btn": "Details",

  // ─── Helper Jobs ───────────────────────────────────────
  "helper_my_job": "My Job",
  "helper_active_job": "Active Job",
  "helper_completed": "Completed",
  "helper_cancelled": "Cancelled",
  "helper_no_jobs": "No jobs found",

  // ─── Helper Job Details ────────────────────────────────
  "job_details_title": "Job Details",
  "job_accept": "Accept Job",
  "job_accepted": "Accepted",
  "job_accepted_success": "Job accepted successfully!",
  "job_sunday": "Sunday, Feb 11, 2026",
  "job_time_range": "10:00 AM - 12:00 PM",
  "job_address": "123 Elm Street, Morocco",
  "job_distance": "2km away",
  "job_customer_info": "Customer Information",
  "job_platform_fee": "Platform Fee (12%)",
  "job_your_earnings": "Your Earnings",
  "job_payment": "Job Payment",
  "job_payment_breakdown": "Online Payment Breakdown",
  "job_payment_note": "Payment will be processed within 24 hours after completion",
  "job_status_submitted": "Submitted",
  "job_status_accepted": "Accepted",
  "job_cancel_reason": "Cancel Reason",
  "job_cancel_reason_default": "Due to unforeseen circumstances, we are unable to proceed with this order at the moment.",
  "job_cancel_reason_hint": "Enter the reason for cancellation",
  "job_cancelled": "Cancelled",
  "job_cancelled_success": "Job has been cancelled",

  // ─── Completed Job ─────────────────────────────────────
  "completed_earned": "Great job! You earned MAD @amount from this order.",

  // ─── Rate Client ───────────────────────────────────────
  "rate_title": "Rate Your Client",
  "rate_skip": "Skip",
  "rate_how_was": "How was your Experience?",
  "rate_leave_review": "Leave a review (Optional)",
  "rate_share": "Share your experience...",
  "rate_submit": "Submit Review",
  "rate_thank_you": "Thank you!",
  "rate_submitted": "Your review has been submitted",

  // ─── Messages ──────────────────────────────────────────
  "messages_title": "Messages",
  "messages_search": "Search chats...",
  "messages_no_messages": "No messages found",

  // ─── Chat ──────────────────────────────────────────────
  "chat_today": "Today",

  // ─── Helper Profile Tab ────────────────────────────────
  "helper_earning": "Earning",
  "helper_buy_connects": "Buy Connects",

  // ─── Earning ───────────────────────────────────────────
  "earning_title": "Earning",
  "earning_revenue": "Revenue",
  "earning_withdrawals": "Withdrawals",
  "earning_fees": "Fees",
  "earning_platform_fees": "Platform Fees",
  "earning_job_earnings": "Job Earnings",
  "earning_no_revenue": "No job earnings yet.",
  "earning_no_fees": "No platform fees yet.",
  "earning_date": "Date",
  "earning_activity": "Activity",
  "earning_method": "Method",
  "earning_from": "From",
  "earning_amount": "Amount",
  "earning_online": "Online",
  "earning_offline": "Offline",
  "earning_clearing": "Clearing",
  "earning_withdrawal": "Withdrawal",
  "earning_transferred": "Transferred successfully",
  "earning_online_earnings": "Online Earnings",
  "earning_offline_earnings": "Offline Earnings",
  "earning_jobs_completed": "Jobs Completed",
  "earning_next": "Next earning",
  "earning_mature_amount": "Current mature amount MAD 300",
  "earning_estimate": "Estimate Payment MAD 300",
  "earning_total": "Total Earnings",

  // ─── Connects ──────────────────────────────────────────
  "connects_title": "Connects",
  "connects_balance": "Available Balance ",
  "connects_view_details": "View details",
  "connects_buy": "Buy Connects",
  "connects_no_history": "No Connects transactions.",
  "connects_recharge_history": "Recharge History",
  "connects_recharge": "Wallet recharge",
  "connects_no_recharges": "No recharges yet.",
  "connects_my_balance": "My balance",
  "connects_select_amount": "Select the amount to buy",
  "connects_new_balance": "Your new Connects balance will be",
  "connects_purchased": "Connects purchased successfully",
  "connects_success": "Success",

  // ─── Add Card ──────────────────────────────────────────
  "card_title": "Add New Card",
  "card_holder_name": "Card Holder Name",
  "card_number": "Card Number",
  "card_expire": "Expire Date",
  "card_cv": "Cv",
  "card_added": "Card added successfully",
  "card_expired_date": "Expired Date",

  // ─── Helper Public Profile ─────────────────────────────
  "public_profile": "Profile",
  "public_edit_info": "Edit Info",
  "public_available": "Available",
  "public_unavailable": "Unavailable",

  // ─── Helper Edit Profile ───────────────────────────────
  "helper_edit_profile": "Profile",
  "helper_personal_info": "Personal Information",
  "helper_phone": "Phone Number",
  "helper_bio": "Bio (optional)",
  "helper_enter_bio": "Enter your bio",
  "helper_save_changes": "Save Changes",
  "helper_saved": "Saved",
  "helper_profile_updated": "Profile updated successfully",
  "helper_add_photos": "Add photos (optional)",
  "helper_availability": "Availability",
  "helper_weekdays": "Available Weekdays",
  "helper_weekends": "Available Weekends",
  "helper_all_days": "Available All Days",
  "helper_pro_info": "Professional Details",
  "helper_hourly_rate": "Hourly Rate (MAD)",
  "helper_experience_years": "Experience (Years)",
  "helper_service_radius": "Service Radius (km)",
  "helper_city": "City",
  "helper_language": "Language",
  "helper_work_samples": "Work Samples (Portfolio)",
  "helper_work_samples_desc": "Upload up to 5 photos of your past work to attract more clients",
  "helper_location_section": "Service Location",
  "helper_search_address": "Search your service address...",
  "helper_use_gps": "Use my current location",
  "helper_max_photos": "You can upload a maximum of 5 photos",

  // ─── Helper Settings ───────────────────────────────────
  "settings_privacy": "Privacy Policy",
  "settings_about": "About Us",
  "settings_help_center": "Help Center",
  "settings_faq": "FAQ",
  "settings_contact_us": "Contact us",
  "settings_faq_title": "Frequently Asked Questions",
  "settings_faq_updated": "This FAQ's last updated was 16 January 2026",
  "settings_support_chat": "Support Chat",
  "settings_24x7_support": "24x7 Online Support",
  "settings_email": "Email",
  "settings_notification": "Notification",

  // ─── Helper Home Tab ───────────────────────────────────
  "helper_tab_search": "Search for a service...",
};
